defaults: 
  -
    scope: 
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "my-site"
  -
    scope:
      path: "projects"
      type: "pages"
    values: 
      layout: "project" #overrides previous default layout
      author: "Mr. Hyde"

sass:
    sass_dir: _sass
    style: compressed