# Name of the site (displayed in the header)
name: Bogdan P.

# Short bio or description (displayed in the header)
description: Web animations - HTML5, CSS3, Javascript

# Includes an icon in the footer for each user name you enter
footer-links:
  github: pbogdan03
  twitter: pbogdan03
  email: p_bogdan03@yahoo.com

# Disqus account 
disqus: wantimator

#
# Standard configuration variables
# 

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# Set the Sass partials directory
sass: 
  sass_dir: _scss
  style: :expanded # or compressed for minified

# Plugins
gems: 
  - jekyll-sitemap 

# Exclude these files from production
exclude: 
  - README.md